school_management/teacher_module/school_management/school_management/urls.py
from django.contrib import admin
from django.urls import path, include
from skill_app import views, AdminViews, StaffViews
from school_management import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('demo', views.showDemoPage),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.ShowLoginPage, name="show_login"),
    path('get_user_details', views.GetUserDetails),
    path('logout_user', views.logout_user, name="logout"),
    path('doLogin', views.doLogin, name="do_login"),
    path('admin_home', AdminViews.admin_home, name="admin_home"),
    path('staff_home', StaffViews.staff_home, name="staff_home"),
    path('add_files_save', StaffViews.add_files_save, name="add_files_save"),
    path('add_agenda_save', StaffViews.add_agenda_save, name="add_agenda_save"),
    path('add_staff', AdminViews.add_staff, name="add_staff"),
    path('staff_agenda', StaffViews.staff_agenda, name="staff_agenda"),
    path('add_files', StaffViews.add_files, name="add_files"),
    path('add_staff_save', AdminViews.add_staff_save, name="add_staff_save"),
    path('add_course', AdminViews.add_course, name="add_course"),
    path('add_course_save', AdminViews.add_course_save, name="add_course_save"),
    path('add_student', AdminViews.add_student, name="add_student"),
    path('add_student_save', AdminViews.add_student_save, name="add_student_save"),
    path('add_subject', AdminViews.add_subject, name="add_subject"),
    path('add_subject_save', AdminViews.add_subject_save, name="add_subject_save"),
    path('check_email_exist', AdminViews.check_email_exist, name="check_email_exist"),
    path('check_teacher_roll_number_exist', AdminViews.check_teacher_roll_number_exist, name="check_teacher_roll_number_exist"),
    path('check_username_exist', AdminViews.check_username_exist, name="check_username_exist"),
    path('check_roll_number_exist', AdminViews.check_roll_number_exist, name="check_roll_number_exist"),
]

school_management/teacher_module/school_management/skill_app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class CustomUser(AbstractUser):
    user_type_data = ((1, "Admin"), (2, "Staff"), (3, "Student"))
    user_type = models.CharField(default=1, choices=user_type_data, max_length=10)


class Admin(models.Model):
    id = models.AutoField(primary_key=True)
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()


class Staffs(models.Model):
    id = models.AutoField(primary_key=True)
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    teacher_roll_number = models.CharField(max_length=50)
    dob = models.DateField()
    blood_group = models.CharField(max_length=10)
    qualification = models.CharField(max_length=50)
    gender = models.CharField(max_length=255)
    profile_pic = models.FileField()
    ph_no = models.CharField(max_length=10)
    address = models.TextField()
    fcm_token = models.TextField(default="")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()

class Files(models.Model):
    classes=models.CharField(max_length=50)
    skills=models.CharField(max_length=50)
    url=models.CharField(max_length=50)
    pdff=models.FileField()    

class Agenda(models.Model):
    classes=models.CharField(max_length=50)
    skills=models.CharField(max_length=50)
    subtopic=models.CharField(max_length=50)
    agenda=models.FileField() 


class Courses(models.Model):
    id = models.AutoField(primary_key=True)
    course_name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()


class Subjects(models.Model):
    id = models.AutoField(primary_key=True)
    subject_name = models.CharField(max_length=255)
    course_id = models.ForeignKey(Courses, on_delete=models.CASCADE, default=1)
    staff_id = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()


class Students(models.Model):
    id = models.AutoField(primary_key=True)
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    gender = models.CharField(max_length=255)
    roll_number = models.CharField(max_length=50)
    blood_group = models.CharField(max_length=10)
    profile_pic = models.FileField()
    ph_no = models.CharField(max_length=10)
    dob = models.DateField()
    fcm_token = models.TextField(default="")
    address = models.TextField()
    course_id = models.ForeignKey(Courses, on_delete=models.DO_NOTHING)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()


@receiver(post_save, sender=CustomUser)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        if instance.user_type == 1:
            Admin.objects.create(admin=instance)
        if instance.user_type == 2:
            Staffs.objects.create(admin=instance, address="", profile_pic="", gender="", ph_no="",
                                  dob="2000-01-01", qualification="", blood_group="", teacher_roll_number="")
        if instance.user_type == 3:
            Students.objects.create(admin=instance, course_id=Courses.objects.get(id=1),
                                    address="", profile_pic="",
                                    gender="", ph_no="", dob="2000-01-01", blood_group="", roll_number="")


@receiver(post_save, sender=CustomUser)
def save_user_profile(sender, instance, **kwargs):
    if instance.user_type == 1:
        instance.admin.save()
    if instance.user_type == 2:
        instance.staffs.save()
    if instance.user_type == 3:
        instance.students.save()

school_management/teacher_module/school_management/skill_app/views.py
import datetime

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from skill_app.EmailBackEnd import EmailBackEnd


def ShowLoginPage(request):
    return render(request, "login_page.html")


def showDemoPage(request):
    return render(request, "demo.html")

def doLogin(request):
    if request.method != "POST":
        return HttpResponse("<h2>Method Not Allowed</h2>")
    else:
        user = EmailBackEnd.authenticate(request, username=request.POST.get("email"),
                                         password=request.POST.get("password"))
        if user != None:
            login(request, user)
            if user.user_type == "1":
                return HttpResponseRedirect('/admin_home')
            elif user.user_type == "2":
                return HttpResponseRedirect(reverse('staff_home'))
            elif user.user_type == "3":
                return HttpResponseRedirect(reverse("/admin_home"))
        else:
            messages.error(request, "Invalid Login Details")
            return HttpResponseRedirect("/")


def GetUserDetails(request):
    if request.user != None:
        return HttpResponse("User : " + request.user.email + " usertype : " + str(request.user.user_type))
    else:
        return HttpResponse("Please Login First")


def logout_user(request):
    logout(request)
    return HttpResponseRedirect("/")

school_management/teacher_module/school_management/skill_app/templates/admin_template/add_course_template.html
{% extends 'admin_template/base_template.html' %}
{% block page_title %}
Add Class
{% endblock page_title %}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
          <div class="row">
              <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Add Class</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="/add_course_save" method="post">
                  {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label>Class </label>
                    <input type="text" class="form-control" name="course" placeholder="Enter Class">
                  </div>

                      <div class="form-group">
                      {% if messages %}
                        {% for message in messages %}
                        {% if message.tags == 'error' %}
                        <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                        <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% endfor %}
                      {% endif %}
                    </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Add Class</button>
                    <button type="reset" class="btn btn-primary float-right">Reset</button>
                </div>
              </form>
            </div>
            <!-- /.card -->



          </div>
          </div>
      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}

school_management/teacher_module/school_management/skill_app/templates/admin_template/add_staff_template.html
{% extends 'admin_template/base_template.html' %}
{% block page_title %}
Add Staff
{% endblock page_title %}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
          <div class="row">
              <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Add Staff</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="/add_staff_save" method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label>Email address</label>
                    <input type="email" class="form-control" name="email" placeholder="Enter email" id="id_email" autocomplete="off">
                  </div>
                  <div class="form-group">
                    <label>Password</label>
                    <input type="password" class="form-control" placeholder="Password" name="password">
                  </div>
                   <div class="form-group">
                    <label>First Name</label>
                    <input type="text" class="form-control" placeholder="First Name" name="first_name">
                  </div>
                   <div class="form-group">
                    <label>Last Name</label>
                    <input type="text" class="form-control" placeholder="Last Name" name="last_name">
                  </div>
                   <div class="form-group">
                    <label>Username</label>
                    <input type="text" class="form-control" placeholder="Username" name="username" id="id_username" autocomplete="off">
                  </div>
                    <div class="form-group">
                    <label>Staff ID</label>
                    <input type="text" class="form-control" placeholder="Enter Staff ID" name="teacher_roll_number" id="id_teacher_roll_number" autocomplete="off">
                  </div>
                    <div class="form-group">
                    <label>Date Of Birth</label>
                    <input type="date" class="form-control" placeholder="Date Of Birth" name="dob">
                  </div>
                    <div class="form-group">
                    <label>Gender</label>
                    <select class="form-control" name="gender">
                            <option>Male</option>
                            <option>Female</option>
                            <option>Other</option>
                    </select>
                    </div>
                     <div class="form-group">
                    <label>Blood Group</label>
                    <input type="text" class="form-control" placeholder="Blood Group" name="blood_group">
                  </div>
                     <div class="form-group">
                    <label>Qualification</label>
                    <input type="text" class="form-control" placeholder="Qualification" name="qualification">
                  </div>
                        <div class="form-group">
                    <label>Profile Picture</label>
                    <input type="file" class="form-control" placeholder="Upload Your Picture" name="profile_pic">
                  </div>

                    <div class="form-group">
                    <label>Phone Number</label>
                    <input type="tel" class="form-control" placeholder="Phone Number" name="ph_no">
                  </div>
                  <div class="form-group">
                    <label>Address</label>
                    <input type="text" class="form-control" placeholder="Address" name="address">
                  </div>
                      <div class="form-group">
                      {% if messages %}
                        {% for message in messages %}
                        {% if message.tags == 'error' %}
                        <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                        <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% endfor %}
                      {% endif %}
                    </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Add Staff</button>
                    <button type="reset" class="btn btn-primary float-right">Reset</button>
                </div>
              </form>
            </div>
            <!-- /.card -->



          </div>
          </div>

      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}
{% block custom_js %}
<script>
    $(document).ready(function(){
        $("#id_email").keyup(function(){
            var email=$(this).val();

           if(email!=""){
                $.ajax({
                    url:'{% url 'check_email_exist' %}',
                    type:'POST',
                    data:{email:email}
                })
                .done(function(response){
                    console.log(response);
                    if(response=="True"){
                        $(".email_error").remove();
                        $("<span class='email_error' style='padding: 5px;color: red;font-weight: bold;'>Email Not Available</span>").insertAfter("#id_email");
                    }
                    else{
                        $(".email_error").remove();
                        $("<span class='email_error' style='padding: 5px;color: green;font-weight: bold;'>Email Available</span>").insertAfter("#id_email");
                    }
                })
                .fail(function(){
                    console.log("failed");
                })
            }
            else{
              $(".email_error").remove();
            }

        });

        $("#id_teacher_roll_number").keyup(function(){
            var teacher_roll_number=$(this).val();

           if(teacher_roll_number!=""){
                $.ajax({
                    url:'{% url 'check_teacher_roll_number_exist' %}',
                    type:'POST',
                    data:{teacher_roll_number:teacher_roll_number}
                })
                .done(function(response){
                    console.log(response);
                    if(response=="True"){
                        $(".teacher_roll_number_error").remove();
                        $("<span class='teacher_roll_number_error' style='padding: 5px;color: red;font-weight: bold;'>ID Not Available</span>").insertAfter("#id_teacher_roll_number");
                    }
                    else{
                        $(".teacher_roll_number_error").remove();
                        $("<span class='teacher_roll_number_error' style='padding: 5px;color: green;font-weight: bold;'>ID Available</span>").insertAfter("#id_teacher_roll_number");
                    }
                })
                .fail(function(){
                    console.log("failed");
                })
            }
            else{
              $(".teacher_roll_number_error").remove();
            }

        });


        $("#id_username").keyup(function(){
            var username=$(this).val();

            if(username!=""){
                $.ajax({
                    url:'{% url 'check_username_exist' %}',
                    type:'POST',
                    data:{username:username}
                })
                .done(function(response){
                    console.log(response);
                    if(response=="True"){
                        $(".username_error").remove();
                        $("<span class='username_error' style='padding: 5px;color: red;font-weight: bold;'>Username Not Available</span>").insertAfter("#id_username");
                    }
                    else{
                        $(".username_error").remove();
                        $("<span class='username_error' style='padding: 5px;color: green;font-weight: bold;'>Username Available</span>").insertAfter("#id_username");
                    }
                })
                .fail(function(){
                    console.log("failed");
                })
            }
            else{
                $(".username_error").remove();
            }

        });

    });
</script>
{% endblock custom_js %}

school_management/teacher_module/school_management/skill_app/templates/admin_template/add_student_template.html
{% extends 'admin_template/base_template.html' %}
{% block page_title %}
Add Student
{% endblock page_title %}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
          <div class="row">
              <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Add Student</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="/add_student_save" method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label>Email address</label>
                    <input type="email" class="form-control" name="email" placeholder="Enter email" id="id_email" autocomplete="off">
                  </div>
                  <div class="form-group">
                    <label>Password</label>
                    <input type="password" class="form-control" placeholder="Password" name="password">
                  </div>
                   <div class="form-group">
                    <label>First Name</label>
                    <input type="text" class="form-control" placeholder="First Name" name="first_name">
                  </div>
                   <div class="form-group">
                    <label>Last Name</label>
                    <input type="text" class="form-control" placeholder="Last Name" name="last_name">
                  </div>
                   <div class="form-group">
                    <label>Username</label>
                    <input type="text" class="form-control" placeholder="Username" name="username" id="id_username" autocomplete="off">
                  </div>
                    <div class="form-group">
                    <label>Date Of Birth</label>
                    <input type="date" class="form-control" placeholder="Date Of Birth" name="dob">
                  </div>

                    <div class="form-group">
                    <label>Gender</label>
                    <select class="form-control" name="gender">
                            <option>Male</option>
                            <option>Female</option>
                            <option>Other</option>
                    </select>
                    </div>
                    <div class="form-group">
                    <label>Blood Group</label>
                    <input type="text" class="form-control" placeholder="Blood Group" name="blood_group">
                  </div>
                    <div class="form-group">
                    <label>Class</label>
                        <select  class="form-control" name="course">
                            {% for course in courses %}
                                <option value="{{ course.id }}">{{ course.course_name }}</option>
                            {% endfor %}
                        </select>
                  </div>
                    <div class="form-group">
                    <label>Roll Number</label>
                    <input type="text" class="form-control" placeholder="Roll Number" name="roll_number" id="id_roll_number" autocomplete="off">
                  </div>
                    <div class="form-group">
                    <label>Profile Picture</label>
                    <input type="file" class="form-control" placeholder="Upload Your Picture" name="profile_pic">
                  </div>

                    <div class="form-group">
                    <label>Phone Number</label>
                    <input type="tel" class="form-control" placeholder="Phone Number" name="ph_no">
                  </div>
                  <div class="form-group">
                    <label>Address</label>
                    <input type="text" class="form-control" placeholder="Address" name="address">
                  </div>

                      <div class="form-group">
                      {% if messages %}
                        {% for message in messages %}
                        {% if message.tags == 'error' %}
                        <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                        <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% endfor %}
                      {% endif %}
                    </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Add Student Details</button>
                    <button type="reset" class="btn btn-primary float-right">Reset</button>
                </div>
              </form>
            </div>
            <!-- /.card -->



          </div>
          </div>
      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}
{% block custom_js %}
<script>
    $(document).ready(function(){
        $("#id_email").keyup(function(){
            var email=$(this).val();

           if(email!=""){
                $.ajax({
                    url:'{% url 'check_email_exist' %}',
                    type:'POST',
                    data:{email:email}
                })
                .done(function(response){
                    console.log(response);
                    if(response=="True"){
                        $(".email_error").remove();
                        $("<span class='email_error' style='padding: 5px;color: red;font-weight: bold;'>Email Not Available</span>").insertAfter("#id_email");
                    }
                    else{
                        $(".email_error").remove();
                        $("<span class='email_error' style='padding: 5px;color: green;font-weight: bold;'>Email Available</span>").insertAfter("#id_email");
                    }
                })
                .fail(function(){
                    console.log("failed");
                })
            }
            else{
              $(".email_error").remove();
            }

        });



        $("#id_roll_number").keyup(function(){
            var roll_number=$(this).val();

           if(roll_number!=""){
                $.ajax({
                    url:'{% url 'check_roll_number_exist' %}',
                    type:'POST',
                    data:{roll_number:roll_number}
                })
                .done(function(response){
                    console.log(response);
                    if(response=="True"){
                        $(".roll_number_error").remove();
                        $("<span class='roll_number_error' style='padding: 5px;color: red;font-weight: bold;'>Roll Number Not Available</span>").insertAfter("#id_roll_number");
                    }
                    else{
                        $(".roll_number_error").remove();
                        $("<span class='roll_number_error' style='padding: 5px;color: green;font-weight: bold;'>Roll Number Available</span>").insertAfter("#id_roll_number");
                    }
                })
                .fail(function(){
                    console.log("failed");
                })
            }
            else{
              $(".roll_number_error").remove();
            }

        });


        $("#id_username").keyup(function(){
            var username=$(this).val();

            if(username!=""){
                $.ajax({
                    url:'{% url 'check_username_exist' %}',
                    type:'POST',
                    data:{username:username}
                })
                .done(function(response){
                    console.log(response);
                    if(response=="True"){
                        $(".username_error").remove();
                        $("<span class='username_error' style='padding: 5px;color: red;font-weight: bold;'>Username Not Available</span>").insertAfter("#id_username");
                    }
                    else{
                        $(".username_error").remove();
                        $("<span class='username_error' style='padding: 5px;color: green;font-weight: bold;'>Username Available</span>").insertAfter("#id_username");
                    }
                })
                .fail(function(){
                    console.log("failed");
                })
            }
            else{
                $(".username_error").remove();
            }

        });

    });
</script>
{% endblock custom_js %}

school_management/teacher_module/school_management/skill_app/templates/admin_template/add_subject_template.html
{% extends 'admin_template/base_template.html' %}
{% block page_title %}
Add Skills
{% endblock page_title %}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
          <div class="row">
              <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Add Skills</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="/add_subject_save" method="post">
                  {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label>Skill </label>
                    <input type="text" class="form-control" name="subject_name" placeholder="Enter Skill">
                  </div>
                  <div class="form-group">
                    <label>Class</label>
                    <select class="form-control" name="course">
                        {% for course in courses %}
                            <option value="{{ course.id }}">{{ course.course_name }}</option>
                        {% endfor %}
                    </select>
                  </div>
                    <div class="form-group">
                    <label>Staff</label>
                        <select class="form-control" name="staff">
                        {% for staff in staffs %}
                            <option value="{{ staff.id }}">{{ staff.first_name }} {{ staff.last_name }}</option>
                        {% endfor %}
                        </select>
                  </div>

                      <div class="form-group">
                      {% if messages %}
                        {% for message in messages %}
                        {% if message.tags == 'error' %}
                        <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                        <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% endfor %}
                      {% endif %}
                    </div>

                  </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Add Skill</button>
                    <button type="reset" class="btn btn-primary float-right">Reset</button>
                </div>
              </form>
            </div>
            <!-- /.card -->



          </div>
          </div>
      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}

school_management/teacher_module/school_management/skill_app/templates/admin_template/footer.html
 <footer class="main-footer">

</footer>

school_management/teacher_module/school_management/skill_app/templates/admin_template/main_content.html
{% extends 'admin_template/base_template.html' %}
{% block page_title %}
Home
{% endblock page_title %}

school_management/teacher_module/school_management/skill_app/templates/staff_template/footer.html
 <footer class="main-footer">

</footer>

school_management/teacher_module/school_management/skill_app/templates/staff_template/main_content.html
{% extends 'staff_template/base_template.html' %}
{% block page_title %}
Home
{% endblock page_title %}